routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','DashboardController@index');

Route::resource('obat','ObatController');
Route::post('obatExcel','ObatController@storeExcel')->name('storeExcel');
Route::get('/obatAjax','ObatController@obatAjax');
Route::post('detailObat','ObatController@detailObat');

Route::resource('interaksi', 'InteraksiController');
Route::get('/interaksiAjax','InteraksiController@InteraksiAjax');

Auth::routes();

Route::resource('bentukObat','BentukObatController');
Route::get('/bentukObatAjax','BentukObatController@bentukObatAjax');

Route::resource('merkDagang','MerkDagangController');
Route::get('/merekDagangAjax','MerkDagangController@merekDagangAjax');

Route::resource('dosis','DosisController');
Route::get('/dosisAjax','DosisController@dosisAjax');

Route::resource('kontraindikasi','KontraindikasiController');
Route::get('/kontraindikasiAjax','KontraindikasiController@kontraindikasiAjax');

Route::resource('pasien','PasienController');
Route::get('/pasienAjax','PasienController@pasienAjax');

Route::resource('resep','ResepController');
Route::get('resepAjax','ResepController@resepAjax');
Route::post('pasienForResep','ResepController@pasienForResep')->name('pasienForResep');
Route::get('/pasienResepAjax','ResepController@pasienResepAjax');
Route::prefix('resep')->group(function(){
	Route::post('show', 'ResepController@show');
	Route::get('{id}/detailResep','ResepController@detailResep')->name('detailResep');
	Route::get('{id}/qr','DetailResepController@qrcode')->name('printResep');
	Route::get('{id}/laporan-pdf','DetailResepController@generatePDF');
	Route::get('{id}/detailResepAjax','DetailResepController@detailResepAjax');
	Route::get('{resepId}/detailResep/{detailObatId}/detailObat','DetailResepController@detail');
});
Route::post('detailObatAjax','ResepController@detailObatAjax');
Route::get('autoCompleteObat','DetailResepController@autoCompleteObat')->name('autoCompleteObat');

Route::resource('detailResep','DetailResepController');

app/Kontraindikasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kontraindikasi extends Model
{
    /*
     * The table associated with the model.
     *
     * @var string
    */
    protected $table = 'kontraindikasi';


    /**
     * Table primary key to define table id
     *
     * @var string
     */
    protected $primaryKey = 'kontraindikasi_id';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'kontraindikasi'
    ];

    // public function detailObat()
    // {
    // 	return $this->hasOne('App\DetailObat','obat_id','obat_id');
    // }

    // public function interaksiObat()
    // {
    //     return $this->hasMany('App\InteraksiObat','obat_id','obat_id');
    // }

    // public function kategoriMapping()
    // {
    //     return $this->hasMany('App\KategoriMapping','obat_id','obat_id');
    // }
}

app/Http/Controllers/KontraindikasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Auth;
use URL;
use session;
use App\Kontraindikasi;

class KontraindikasiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('kontraindikasi.index');
    }

    //ajax datatable
    public function kontraindikasiAjax()
    {
        $data = Kontraindikasi::all();
        $listKategori ='';
        // return $data;
        return datatables()->of($data)
            ->addColumn('action',function($data){
                $button = '';
                $button .= '<form id="myform" method="post" action="'.route('kontraindikasi.destroy',$data->kontraindikasi_id).'">
                                '.csrf_field().'
                                <a href="' .URL::to('/kontraindikasi/' . $data->kontraindikasi_id . '/edit'). '" class="btn btn-sm btn-warning"><i class="fas fa-edit mr-1"></i> Edit</a>
                                <input name="_method" type="hidden" value="DELETE">
                                <button type="submit" class="btn btn-danger btn-sm" ><i class="far fa-trash-alt mr-1"></i> Delete</button>
                            </form>';
                return $button;
            })
            ->removeColumn('updated_at')
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
        return view('kontraindikasi.create');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'kontraindikasi' => 'required'
        ]);

        DB::beginTransaction();
        try {
            $kontraindikasi = new Kontraindikasi;
            $kontraindikasi->kontraindikasi = $request->kontraindikasi;
            $kontraindikasi->added_by = Auth::user()->id;
            $kontraindikasi->save();
            DB::commit();
            return redirect()->route('kontraindikasi.index')->with('success','Merk dagang berhasil ditambahkan');
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('pasien.create')->with('error','Ada yang tidak beres silahkan hubungi pengembang');
        }
    }

    public function edit($id)
    {
        $kontraindikasi = Kontraindikasi::findOrFail($id);
        return view('kontraindikasi.edit',compact('kontraindikasi'));
    }

    public function update(Request $request,$id)
    {
        $this->validate($request,[
            'kontraindikasi' => 'required'
        ]);
        try {
            $kontraindikasi = Kontraindikasi::findOrFail($id);
            $kontraindikasi->kontraindikasi = $request->kontraindikasi;
            $kontraindikasi->save();
            DB::commit();
            return redirect()->route('kontraindikasi.index')->with('success','Merk dagang berhasil diubah');
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('kontraindikasi.edit',$id)->with('error','Ada yang tidak beres silahkan hubungi pengembang');
        }
    }

    public function destroy($id)
    {
        try {
            $kontraindikasi = Kontraindikasi::findOrFail($id);
            $kontraindikasi->delete();
            DB::commit();
            return redirect()->route('kontraindikasi.index')->with('success','Merk dagang berhasil dihapus');
        } catch (Exception $e) {
            DB::rollback();
            return redirect()->route('kontraindikasi.index')->with('error','Ada yang tidak beres silahkan hubungi pengembang');
        }
    }
}

resources/views/kontraindikasi/create.blade.php
@extends('layouts.app')

	@section('content')
		@if ($errors->any())
	        <div class="box-body col-12 col-md-12 col-lg-12">
	            <div class="alert alert-danger alert-dismissible">
	                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	                <h4><i class="icon fa fa-ban"></i> Error!</h4>
	                <ul>
	                    @foreach ($errors->all() as $error)
	                        <li>{{ $error }}</li>
	                    @endforeach
	                </ul>
	            </div>
	        </div>
	    @endif
		@if (session('error'))
	        <div class="box-body">
	            <div class="alert alert-danger alert-dismissible">
	                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	                <h4><i class="icon fa fa-ban"></i> Error!</h4>
	                    {{ session('error') }}
	            </div>
	        </div>
	    @endif
		{{-- start breadcrumb --}}
		<div class="card page-header page-header-light">
		    <div class="page-header-content header-elements-md-inline">
		        <div class="page-title">
		            <h2><span class="font-weight-semibold mx-2">APOTECH</span> - Tambah kontraindikasi baru</h2>
		        </div>
		    </div>
		    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
			    <div class="d-flex">
			        <div class="breadcrumb">
			            <a href="{{ URL::to('/kontraindikasi')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>kontraindikasi</a>
			            <span class="breadcrumb-item active">Create</span>
			        </div>
			    </div>
			</div>
		</div>
		{{-- end breadcrumb --}}
		
		<div class="card">
			<div class="card-header header-elements-inline">
				<h5 class="card-title">Kontraindikasi</h5>
				<div class="header-elements">
					<div class="list-icons">
                		<a class="list-icons-item" data-action="collapse"></a>
                		<a class="list-icons-item" data-action="reload"></a>
                		<a class="list-icons-item" data-action="remove"></a>
                	</div>
            	</div>
			</div>

			<div class="card-body">
				<form action="{{ route('kontraindikasi.store') }}" method="post" enctype="multipart/form-data">
					{{ csrf_field() }}
					<div class="form-group">
						<label>Kontraindikasi value:</label>
						<input type="text" class="form-control" placeholder="Silahkan masukan value kontraindikasi" name="kontraindikasi">
					</div>
					<div class="text-right">
						<a type="button" class="btn btn-warning" href="{{ URL::to('/kontraindikasi') }}"><i class="fas fa-long-arrow-alt-left mr-1"></i>Back</a>
						<button type="submit" class="btn btn-primary">Submit<i class="icon-paperplane ml-2"></i></button>
					</div>
				</form>
			</div>
		</div>
	@endsection
@section('librariesJS')
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/demo_pages/datatables_basic.js') }}"></script>
@endsection
@section('script')
@endsection

resources/views/kontraindikasi/edit.blade.php
@extends('layouts.app')

@section('content')
	@if ($errors->any())
        <div class="box-body col-12 col-md-12 col-lg-12">
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i> Error!</h4>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    @endif
	@if (session('error'))
        <div class="box-body">
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i> Error!</h4>
                    {{ session('error') }}
            </div>
        </div>
    @endif
	{{-- start breadcrumb --}}
	<div class="card page-header page-header-light">
		    <div class="page-header-content header-elements-md-inline">
		        <div class="page-title">
		            <h2><span class="font-weight-semibold mx-2">APOTECH</span> - Ubah kontraindikasi</h2>
		        </div>
		    </div>
		    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
			    <div class="d-flex">
			        <div class="breadcrumb">
			            <a href="{{ URL::to('/kontraindikasi')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>Kontraindikasi</a>
			            <span class="breadcrumb-item active">Edit</span>
			        </div>
			    </div>
			</div>
		</div>
	{{-- end breadcrumb --}}
	
	<div class="card">
		<div class="card-header header-elements-inline">
			<h5 class="card-title">Kontraindikasi</h5>
			<div class="header-elements">
				<div class="list-icons">
            		<a class="list-icons-item" data-action="collapse"></a>
            		<a class="list-icons-item" data-action="reload"></a>
            		<a class="list-icons-item" data-action="remove"></a>
            	</div>
        	</div>
		</div>

		<div class="card-body">
			<form action="{{ route('kontraindikasi.update',$kontraindikasi->kontraindikasi_id) }}" method="post" enctype="multipart/form-data">
				{{ csrf_field() }}
				{{ method_field('PUT') }}
				<div class="form-group">
					<label>Obat</label>
					<select class="form-control" name="obat">
						<option>1</option>
						<option>2</option>
					</select>
				</div>
				<div class="form-group">
					<label>Kontraindikasi name:</label>
					<input type="text" class="form-control" placeholder="Silahkan masukan nama mek dagang" value="{{ $kontraindikasi->kontraindikasi }}" name="kontraindikasi">
				</div>
				<div class="text-right">
					<a class="btn btn-warning" href="{{ URL::to('/kontraindikasi') }}"><i class="fas fa-long-arrow-alt-left mr-1"></i>Back</a>
					<button type="submit" class="btn btn-primary">Submit<i class="icon-paperplane ml-2"></i></button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/kontraindikasi/index.blade.php
@extends('layouts.app')

	@section('content')
        @if ($errors->any())
            <div class="box-body col-12 col-md-12 col-lg-12">
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Error!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        @if (session('success'))
            <div class="box-body">
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Success!</h4>
                        {{ session('success') }}
                </div>
            </div>
        @endif
        @if (session('error'))
            <div class="box-body">
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Error!</h4>
                        {{ session('error') }}
                </div>
            </div>
        @endif
	   {{-- start breadcrumb --}}
        <div class="card page-header page-header-light">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title">
                    <h2><span class="font-weight-semibold mx-2">APOTECH</span> - Kontraindikasi</h2>
                </div>
            </div>
            <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
                <div class="d-flex">
                    <div class="breadcrumb">
                        <a href="{{ URL::to('/kontraindikasi')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>Kontraindikasi</a>
                        <span class="breadcrumb-item active">Dashboard</span>
                    </div>
                </div>
            </div>
        </div>
        {{-- end breadcrumb --}}
		
		<div class="card">
	        <div class="card-header">
	        	<a class="btn btn-primary" href="{{URL::to('/kontraindikasi/create')}}"><i class="far fa-plus-square mr-2"></i>Tambah kontraindikasi baru</a>
	        </div>
	        <div class="card-body">
	            <div class="table-responsive">
	                <table class="table table-striped" id="table">
	                    <thead>
	                        <tr>
	                            <th class="text-center" width="10%">
	                                ID
	                            </th>
                                <th>Kontraindikasi</th>
	                            <th width="30%">Action</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                    </tbody>
	                </table>
	            </div>
	        </div>
	    </div>
	@endsection
@section('librariesJS')
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/demo_pages/datatables_basic.js') }}"></script>
@endsection
@section('script')
	<script>
		$(document).ready(function() {
            console.log("cek ready");
            $("#table").DataTable({
                "destroy": true,
                "processing": true,
                "serverSide": true,
                "ajax": {'url':"{{ url('kontraindikasiAjax') }}",
                        'headers':"{{ csrf_token() }}"},
                "order": ['0', 'desc'],
                "dataSrc": "data",
                "columns": [
                    {data: 'kontraindikasi_id', name: 'kontraindikasi_id'},
                    {data: 'kontraindikasi', name: 'kontraindikasi'},
                    {data: 'action', name: 'action', "orderable": false, "searchable": false}
                ],
                "fixedColumns": true,
            });
        });
	</script>
@endsection