routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','DashboardController@index');

Route::resource('obat','ObatController');
Route::post('obatExcel','ObatController@storeExcel')->name('storeExcel');
Route::get('/obatAjax','ObatController@obatAjax');
Route::post('detailObat','ObatController@detailObat');

Route::resource('interaksi', 'InteraksiController');
Route::get('/interaksiAjax','InteraksiController@InteraksiAjax');

Auth::routes();

Route::resource('bentukObat','BentukObatController');
Route::get('/bentukObatAjax','BentukObatController@bentukObatAjax');

Route::resource('merkDagang','MerkDagangController');
Route::get('/merekDagangAjax','MerkDagangController@merekDagangAjax');

Route::resource('dosis','DosisController');
Route::get('/dosisAjax','DosisController@dosisAjax');

Route::resource('kontraindikasi','KontraindikasiController');
Route::get('/kontraindikasiAjax','KontraindikasiController@kontraindikasiAjax');

Route::resource('pasien','PasienController');
Route::get('/pasienAjax','PasienController@pasienAjax');

Route::resource('resep','ResepController');
Route::get('resepAjax','ResepController@resepAjax');
Route::post('pasienForResep','ResepController@pasienForResep')->name('pasienForResep');
Route::get('/pasienResepAjax','ResepController@pasienResepAjax');
Route::prefix('resep')->group(function(){
	Route::post('show', 'ResepController@show');
	Route::get('{id}/detailResep','ResepController@detailResep')->name('detailResep');
	Route::get('{id}/qr','DetailResepController@qrcode')->name('printResep');
	Route::get('{id}/laporan-pdf','DetailResepController@generatePDF');
	Route::get('{id}/detailResepAjax','DetailResepController@detailResepAjax');
	Route::get('{resepId}/detailResep/{detailObatId}/detailObat','DetailResepController@detail');
});
Route::post('detailObatAjax','ResepController@detailObatAjax');
Route::get('autoCompleteObat','DetailResepController@autoCompleteObat')->name('autoCompleteObat');

Route::resource('detailResep','DetailResepController');

app/BentukObat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BentukObat extends Model
{
    /*
     * The table associated with the model.
     *
     * @var string
    */
    protected $table = 'bentuk_obat';


    /**
     * Table primary key to define table id
     *
     * @var string
     */
    protected $primaryKey = 'bentuk_obat_id';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'bentuk'
    ];
}

app/Http/Controllers/BentukObatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use URL;
use session;
use App\BentukObat;

class BentukObatController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('bentukObat.index');
    }

    //ajax datatable
    public function bentukObatAjax()
    {
        $data = BentukObat::all();
        // return $data;
        return datatables()->of($data)
            ->addColumn('action',function($data){
                $button = '';
                $button .= '<form id="myform" method="post" action="'.route('bentukObat.destroy',$data->bentuk_obat_id).'">
                                '.csrf_field().'
                                <a href="' .URL::to('/bentukObat/' . $data->bentuk_obat_id . '/edit'). '" class="btn btn-sm btn-warning"><i class="fas fa-edit mr-1"></i> Edit</a>
                                <input name="_method" type="hidden" value="DELETE">
                                <button type="submit" class="btn btn-danger btn-sm" ><i class="far fa-trash-alt mr-1"></i> Delete</button>
                            </form>';
                return $button;
            })
            ->removeColumn('updated_at')
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bentukObat.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'bentukObatName' => 'required|string'
        ]);

        DB::beginTransaction();
        try{
          $bentukObat = new BentukObat;
          $bentukObat->bentuk = $request->bentukObatName;
          $bentukObat->save();
          DB::commit();
          return redirect()->route('bentukObat.index')->with('success','Bentuk obat berhasil ditambahkan');
        }catch(\Exception $e){
            DB::rollback();
            return redirect()->route('bentukObat.create')->with('error','Ada yang tidak beres silahkan hubungi pengembang');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Obat  $obat
     * @return \Illuminate\Http\Response
     */
    public function show(Obat $obat)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Obat  $obat
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bentukObat = BentukObat::findOrFail($id);
        return view('bentukObat.edit',compact('bentukObat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Obat  $obat
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // return $request['obatKategori'];
         $this->validate($request,[
            'bentukObatName' => 'required|string'
        ]);

        DB::beginTransaction();
        try{
            $bentukObat = BentukObat::findOrFail($id);
            $bentukObat->bentuk = $request->bentukObatName;
            $bentukObat->save();
            DB::commit();
            return redirect()->route('bentukObat.index')->with('success','bentuk obat berhasil diubah');
        }catch(\Exception $e){
            DB::rollback();
            return redirect()->route('bentukObat.edit',$id)->with('error','Ada yang tidak beres silahkan hubungi pengembang');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Obat  $obat
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try{
          $bentukObat = BentukObat::findOrFail($id);
          $bentukObat->delete();
          DB::commit();
          return redirect()->route('bentukObat.index')->with('success','Bentuk obat deleted successfully');
        }catch(\Exception $e){
          DB::rollback();
          return redirect()->route('bentukObat.index')->with('error','Ada yang tidak beres silahkan hubungi pengembang');
        }
    }
}

resources/views/bentukObat/create.blade.php
@extends('layouts.app')

	@section('content')
		@if ($errors->any())
	        <div class="box-body col-12 col-md-12 col-lg-12">
	            <div class="alert alert-danger alert-dismissible">
	                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	                <h4><i class="icon fa fa-ban"></i> Error!</h4>
	                <ul>
	                    @foreach ($errors->all() as $error)
	                        <li>{{ $error }}</li>
	                    @endforeach
	                </ul>
	            </div>
	        </div>
	    @endif
	    
	    @if (session('error'))
	        <div class="box-body">
	            <div class="alert alert-danger alert-dismissible">
	                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	                <h4><i class="icon fa fa-ban"></i> Error!</h4>
	                    {{ session('error') }}
	            </div>
	        </div>
	    @endif
		{{-- start breadcrumb --}}
		<div class="card page-header page-header-light">
		    <div class="page-header-content header-elements-md-inline">
		        <div class="page-title">
		            <h2><span class="font-weight-semibold mx-2">APOTECH</span> - Tambah betuk obat baru</h2>
		            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
		        </div>
		    </div>
		    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
			    <div class="d-flex">
			        <div class="breadcrumb">
			            <a href="{{ URL::to('/interaksi')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>Bentuk Obat</a>
			            <span class="breadcrumb-item active">Create</span>
			        </div>
			        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
			    </div>
			</div>
		</div>
		{{-- end breadcrumb --}}
		
		<div class="card">
			<div class="card-header header-elements-inline">
				<h5 class="card-title">Bentuk Obat</h5>
				<div class="header-elements">
					<div class="list-icons">
                		<a class="list-icons-item" data-action="collapse"></a>
                		<a class="list-icons-item" data-action="reload"></a>
                		<a class="list-icons-item" data-action="remove"></a>
                	</div>
            	</div>
			</div>

			<div class="card-body">
				<form action="{{ route('bentukObat.store') }}" method="post" enctype="multipart/form-data">
					{{ csrf_field() }}
					<div class="form-group">
						<label>Nama Bentuk Obat:</label>
						<input type="text" class="form-control" placeholder="Silahkan masukan nama bentuk obat yang baru" name="bentukObatName">
					</div>
					<div class="text-right">
						<a class="btn btn-warning" href="{{ URL::to('/bentukObat') }}"><i class="fas fa-long-arrow-alt-left mr-1"></i>Back</a>
						<button type="submit" class="btn btn-primary">Submit<i class="icon-paperplane ml-2"></i></button>
					</div>
				</form>
			</div>
		</div>
	@endsection
@section('librariesJS')
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/demo_pages/datatables_basic.js') }}"></script>
@endsection
@section('script')
@endsection

resources/views/bentukObat/edit.blade.php
@extends('layouts.app')

@section('content')

	@if ($errors->any())
        <div class="box-body col-12 col-md-12 col-lg-12">
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i> Error!</h4>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    @endif
    
    @if (session('error'))
        <div class="box-body">
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i> Error!</h4>
                    {{ session('error') }}
            </div>
        </div>
    @endif
    
	{{-- start breadcrumb --}}
	<div class="card page-header page-header-light">
		    <div class="page-header-content header-elements-md-inline">
		        <div class="page-title">
		            <h2><span class="font-weight-semibold mx-2">APOTECH</span> - Ubah bentuk obat</h2>
		        </div>
		    </div>
		    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
			    <div class="d-flex">
			        <div class="breadcrumb">
			            <a href="{{ URL::to('/bentukObat')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>Bentuk obat</a>
			            <span class="breadcrumb-item active">Edit</span>
			        </div>
			    </div>
			</div>
		</div>
	{{-- end breadcrumb --}}
	
	<div class="card">
		<div class="card-header header-elements-inline">
			<h5 class="card-title">Bentuk Obat</h5>
			<div class="header-elements">
				<div class="list-icons">
            		<a class="list-icons-item" data-action="collapse"></a>
            		<a class="list-icons-item" data-action="reload"></a>
            		<a class="list-icons-item" data-action="remove"></a>
            	</div>
        	</div>
		</div>

		<div class="card-body">
			<form action="{{ route('bentukObat.update',$bentukObat->bentuk_obat_id) }}" method="post" enctype="multipart/form-data">
				{{ csrf_field() }}
				{{ method_field('PUT') }}
				<div class="form-group">
					<label>Bentuk :</label>
					<input type="text" class="form-control" value="{{ $bentukObat->bentuk }}" placeholder="Silahkan masukan bentuk obat" name="bentukObatName">
				</div>
				<div class="text-right">
					<a class="btn btn-warning" href="{{ URL::to('/bentukObat') }}"><i class="fas fa-long-arrow-alt-left mr-1"></i>Back</a>
					<button type="submit" class="btn btn-primary">Submit<i class="icon-paperplane ml-2"></i></button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/bentukObat/index.blade.php
@extends('layouts.app')

	@section('content')

        @if ($errors->any())
            <div class="box-body col-12 col-md-12 col-lg-12">
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Error!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        
        @if (session('success'))
            <div class="box-body">
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Success!</h4>
                        {{ session('success') }}
                </div>
            </div>
        @endif

        @if (session('error'))
            <div class="box-body">
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Error!</h4>
                        {{ session('error') }}
                </div>
            </div>
        @endif
        
	    {{-- start breadcrumb --}}
        <div class="card page-header page-header-light">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title">
                    <h2><span class="font-weight-semibold mx-2">APOTECH</span> - Bentuk Obat</h2>
                </div>
            </div>
            <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
                <div class="d-flex">
                    <div class="breadcrumb">
                        <a href="{{ URL::to('/interaksi')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i>Bentuk Obat</a>
                        <span class="breadcrumb-item active">Dashboard</span>
                    </div>
                </div>
            </div>
        </div>
        {{-- end breadcrumb --}}
		
		<div class="card">
	        <div class="card-header">
	        	<a class="btn btn-primary" href="{{URL::to('/bentukObat/create')}}"><i class="far fa-plus-square mr-2"></i>Tambah bentuk obat baru</a>
	        </div>
	        <div class="card-body">
	            <div class="table-responsive">
	                <table class="table table-striped" id="table">
	                    <thead>
	                        <tr>
	                            <th class="text-center" width="10%">
	                                ID
	                            </th>
	                            <th>Bentuk Obat</th>
	                            <th width="30%">Action</th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                    </tbody>
	                </table>
	            </div>
	        </div>
	    </div>
	@endsection
@section('librariesJS')
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('limitless/Template/global_assets/js/demo_pages/datatables_basic.js') }}"></script>
@endsection
@section('script')
	<script>
		$(document).ready(function() {
            console.log("cek ready");
            $("#table").DataTable({
                "destroy": true,
                "processing": true,
                "serverSide": true,
                "ajax": {'url':"{{ url('bentukObatAjax') }}",
                        'headers':"{{ csrf_token() }}"},
                "order": ['0', 'desc'],
                "dataSrc": "data",
                "columns": [
                    {data: 'bentuk_obat_id', name: 'bentuk_obat_id'},
                    {data: 'bentuk', name: 'bentuk'},
                    {data: 'action', name: 'action', "orderable": false, "searchable": false}
                ],
                "fixedColumns": true,
            });
        });
	</script>
@endsection